### ISSUE TITLE
[FEATURE] Continuous Benchmarking

### ISSUE THREAD

**Issue by pioardi** [poolifier/poolifier#106]
This is what I would like at the end of the game on benchmarking:
https://github.com/fastify/fastify#benchmarks

This is what they do :
https://github.com/fastify/benchmarks/blob/master/.github/workflows/benchmarks.yml

They run benchmarks on a schedule and then publish results into their readme, continuous benchmarking with poolifier that win on everything else 🔥 👊 🏆

So to work on this issue we should first of all write all the benchmarks that we need and organize the output, then create a github workflow that run benchs on a schedule and publish results into a readme section ( or something similar )

**Comment by Shinigami92** [comment]
We should also add more benchmarks to other libs like
- https://github.com/piscinajs/piscina
- https://github.com/kevlened/threadwork

**Comment by pioardi** [comment]
Yes we should include piscina into our benchmarks, will be interesting that project is written by 3 node gurus but I am confident to run faster then them( there is a reason why I am confident, but we will look into this at proper time bro)

**Comment by jerome-benoit** [comment]
https://github.com/SUCHMOKUO/node-worker-threads-pool

**Comment by pioardi** [comment]
https://github.com/andywer/threads.js
https://github.com/wilk/microjob

**Comment by jerome-benoit** [comment]
I think the CI integration is still needed ;)

**Comment by pioardi** [comment]
Yes Github closed the issue directly, not only the CI but also bench with other pools and another small thing that allow us to change the function under benchmark more dynamically.

For CI we cannot really leverage on GitHub ( unpaid ) multi-tenant runners because they run also other jobs and this could impact our bench....so for that we will need funds.

**Comment by jerome-benoit** [comment]
+ https://github.com/piscinajs/piscina: done
+ https://github.com/kevlened/threadwork: done
+ https://github.com/andywer/threads.js: done
+ https://github.com/wilk/microjob: done
+ https://github.com/watson/worker-threads-pool: done
+ https://github.com/josdejong/workerpool: done

**Comment by jerome-benoit** [comment]
To evaluate: 

+ https://github.com/Truth1984/thread_pools

**Comment by pioardi** [comment]
I would consider node-worker-nodes but not the thread_pools library since has only 1 star

**Comment by jerome-benoit** [comment]
> I would consider node-worker-nodes but not the thread_pools library since has only 1 star

Reference: 6c06373320e61af1078a265851a15711a97b08af

**Comment by jerome-benoit** [comment]
To evaluate:

+ tinypool: https://www.npmjs.com/package/tinypool

**Comment by jerome-benoit** [comment]
Done: 

+ worker-nodes: https://github.com/allegro/node-worker-nodes
+ tinypool: https://github.com/tinylibs/tinypool

Removed: 

+ microjob
+ threads.js
+ threadworks

**Comment by jerome-benoit** [comment]
To evaluate: 

+ nanothreads: https://github.com/snuffyDev/nanothreads

**Comment by jerome-benoit** [comment]
To evaluate: 

+ @rushstack/worker-pool: https://github.com/microsoft/rushstack/tree/main/libraries/worker-pool

**Comment by jerome-benoit** [comment]
Continuous internal benchmark: https://github.com/poolifier/poolifier/commit/f1c674cd6caabfbe46bc99d412611b4a91727c5f

**Comment by jerome-benoit** [comment]
Hyperfine GH action: https://github.com/blacha/hyperfine-action

**Comment by jerome-benoit** [comment]
Done in https://github.com/poolifier/benchmark
