### ISSUE TITLE
[FEATURE] Port poolifier to Bun

### ISSUE THREAD

**Issue by jerome-benoit** [poolifier/poolifier#1361]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Bun is the fastest JS runtime at the time

From the Deno poolifier portage to web worker: 
- [x] Generate a npm package with `dnt`: poolifier-web-worker
- [ ] Add bun specific tests for that npm package to CI

**Comment by jerome-benoit** [comment]
> Is there a better way to achieve this without forking and maintaining two separate codebases?

I doubt it. And in any case, the first step is to test current bun support regarding `worker_threads`. And the initial portage work is far from working. Bun `worker_threads` support does not seem to be stable enough yet to execute poolifier code without fixing bun.

**Comment by jerome-benoit** [comment]
Required upstream PRs:
+ https://github.com/oven-sh/bun/pull/6521

**Comment by calumk** [comment]
Looking forward to using this with bun

**Comment by jerome-benoit** [comment]
> Looking forward to using this with bun

Given the current state of bun worker_threads integration, that will not happen anytime soon: most poolifier tests fail or hang.   

I think making a package from the Deno portage using standardized web workers will likely work sooner with bun, given that web workers need only stabilisation work.

**Comment by jerome-benoit** [comment]
Initial npm release done: https://www.npmjs.com/package/poolifier-web-worker
