### ISSUE TITLE
[BUG] New async task start before previously async task end

### ISSUE THREAD

**Issue by andgest** [poolifier/poolifier#1626]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello
I want to wait that my fist async task finished before running the next task.
In the following code I run 3 async tasks with a wait of 1 seconds on a single worker.
I expect that my next task wait the previous to start.
But all my task start even if previous is not finished.
How can I do to force to wait that my async process is finished to start the next task ?

### Expected behavior

My exepected log are the following :

1 - Start processing
1 - Completed processing
2 - Start processing
2 - Completed processing
3 - Start processing
3 - Completed processing

### Actual behavior

My actual log are the following :

1 - Start processing
2 - Start processing
3 - Start processing
1 - Completed processing
2 - Completed processing
3 - Completed processing

### Steps to reproduce

To reproduce you can run the following code

My main code

```ts
import {FixedThreadPool} from "poolifier";
class Main {
  constructor() {
    const pool = new FixedThreadPool(1, ".worker.js", {
      enableEvents: true,
      enableTasksQueue: true,
      tasksQueueOptions: {
        size: undefined,
        concurrency: 1,
        taskStealing: false,
        tasksStealingOnBackPressure: false
      }
    });

    const count = 0;
    for (let i = 1; i <= 3; i++) {
      pool.execute(i).then(() => {
        console.log("Task " + i + " finished");
      })
    }
  }
}
```

My worker code : "worker.js"

```ts
import {
  ThreadWorker,
  WorkerOptions,
} from "poolifier";

class SsrThreadWorker extends ThreadWorker<number, string | undefined> {
  constructor() {
    super(async (id: number) => await this.process(id), {
      maxInactiveTime: 20000, // ms
      killBehavior: "SOFT",
      killHandler: () => {
        // eslint-disable-next-line no-console
        console.error("Worker killed");
      },
    } as WorkerOptions);
  }

  private async sleep(id: number, ms: number): Promise<string> {
    return new Promise((resolve, reject) => {
      setTimeout(() => resolve("Wait " + ms + "ms in task " + id), ms);
    });
  }

  private async process(id: number): Promise<string> {
    console.log(id + " - Start processing");
    const result = await this.sleep(id, 1000);
    console.log(id + " - Completed processing");
    return result;
  }
}

export default new SsrThreadWorker();
```

### poolifier version

3.0.5

### Node.js version

18.16.0

### System

System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 3.54 GB / 30.94 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash

**Comment by jerome-benoit** [comment]
Thread pool goal is to allow to run tasks in parallel in a ressource regulated way. 
A use case that is not designed to run tasks in parallel is by definition not covered by poolifier (https://en.wikipedia.org/wiki/Embarrassingly_parallel). 

But if you really want to run sequentially tasks with poolifier at the cost of using way more resources than needed to do it: 

```ts
pool = new FixedThreadPool()

for (const task of [task1Data, task2Data, ... ]) {
    await pool.execute(task)
}
```

**Comment by andgest** [comment]
Thank you for your reply.
Indeed, it corrects my problem
I don't understand how await works.
I thought it would block my main process by using it on the execute.

My use case is for an express js application that does Server Side Rendering on workers.
The aim is to perform heavy SSR processing on the worker and cache the result, and in the meantime allow express js to respond to the client with the default page.

**Comment by jerome-benoit** [comment]
> My use case is for an express js application that does Server Side Rendering on workers. The aim is to perform heavy SSR processing on the worker and cache the result, and in the meantime allow express js to respond to the client with the default page.

Then make your SSR code delightfully parallel: reentrant and atomic to really benefit from offloading it to a thread pool.

**Comment by andgest** [comment]
In fact no, this does not block my main thread but **my tasks continue to execute all together**

**Comment by jerome-benoit** [comment]
In any case, it's neither a bug nor an unexpected behavior for a thread pool: 

+ The promise used in poolifier `execute()` resolve only **once** the submitted task is finished
+ Tasks are executed in **parallel** in different threads  in the pool
+ The whole point of using poolifier is to avoid to block the main thread ... 

I think there's a misunderstanding of what poolifier is expected to be used for and how. 

If you expect parallel execution to end in the submitted order, that will never ever happen per design and definition parallelism.

**Comment by andgest** [comment]
Thank you for this clarification
I thought that parallelization on multiple threads was done between each worker and not within a worker.
