### ISSUE TITLE
[BUG] Dynamic pool with min = 0 fails to execute a task once the pool size has shrunk to 0

### ISSUE THREAD

**Issue by indrodev** [poolifier/poolifier#1748]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Error: Worker node key chosen is null or undefined after 6 retries at L.execute (/usr/src/app/node_modules/poolifier/lib/index.js:1:14589) at exports.DynamicThreadPool.chooseWorkerNode (/usr/src/app/node_modules/poolifier/lib/index.js:1:36288) at /usr/src/app/node_modules/poolifier/lib/index.js:1:32596 at new Promise (<anonymous>) at exports.DynamicThreadPool.execute (/usr/src/app/node_modules/poolifier/lib/index.js:1:32044) at HttpModeTask.process (/usr/src/app/dist/lib/Task/task.service.js:450:18) at HttpModeTask.execute (/usr/src/app/dist/lib/Task/task.service.js:264:32) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.processJob [as fn] (/usr/src/app/dist/utils/agenda/jobs/task.js:22:24) { [stack]: 'Error: Worker node key chosen is null or undefined after 6 retries\n' + ' at L.execute (/usr/src/app/node_modules/poolifier/lib/index.js:1:14589)\n' + ' at exports.DynamicThreadPool.chooseWorkerNode (/usr/src/app/node_modules/poolifier/lib/index.js:1:36288)\n' + ' at /usr/src/app/node_modules/poolifier/lib/index.js:1:32596\n' + ' at new Promise (<anonymous>)\n' + ' at exports.DynamicThreadPool.execute (/usr/src/app/node_modules/poolifier/lib/index.js:1:32044)\n' + ' at HttpModeTask.process (/usr/src/app/dist/lib/Task/task.service.js:450:18)\n' + ' at HttpModeTask.execute (/usr/src/app/dist/lib/Task/task.service.js:264:32)\n' + ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + ' at async Object.processJob [as fn] (/usr/src/app/dist/utils/agenda/jobs/task.js:22:24)', [message]: 'Worker node key chosen is null or undefined after 6 retries' }

### Expected behavior

no error

### Actual behavior

throws error

### Steps to reproduce

It occurs randomly while using DynamicThreadPool

### poolifier version

3.0.9

### Node.js version

20.10.0

**Comment by jerome-benoit** [comment]
Could you please please test version 3.0.13?

**Comment by indrodev** [comment]
> More information is needed:
> 
> * pool configuration
> * task function
> * stack trace with [--enable-source-maps](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_enable_source_maps)
> 
> Basically, the complete poolifier usage to reproduce it. And ideally a small standalone reproduction case.

will try to create a small project replicating this issue, but I've observed till now it's mostly random.



> Could you please test version 3.0.13 or superior?

Yes, 3.0.14 had the same issue / error. Currently on 3.1.3, will update to the latest version. I'll let you know if issue arise.

**Comment by jerome-benoit** [comment]
> > Basically, the complete poolifier usage to reproduce it. And ideally a small standalone reproduction case.
> 
> will try to create a small project replicating this issue, but I've observed till now it's mostly random.
> 

It's not random, there's conditions triggering it and the list is quite short: 

- No worker nodes are ready
- Worker choice strategy algo is buggy

That's why the pool options used was asked.

**Comment by indrodev** [comment]
Example Interface file -

```typescript
import { DynamicThreadPool, availableParallelism } from "poolifier";
const MAX_POOL_SIZE = availableParallelism() > 1 ? availableParallelism() - 1 : 1;

export const poolProcessHttp = new DynamicThreadPool<HttpWP, Promise<HttpWR>>(
    0,
    MAX_POOL_SIZE,
    PROCESS_HTTP_WORKER_PATH,
    {
        workerOptions: {
            name: "Http Worker",
        },
        errorHandler: (e: Error) => {
            logger.error("error in http worker %o", e);
            return e;
        },
        onlineHandler: () => {
            logger.info("HTTP Worker is online");
        },
    }
);

```

Example Worker file -
```typescript
import { ThreadWorker } from "poolifier";
import { z } from "zod";
import { processTask } from "../../helper";
import { MakeHttpJsonCallResponse } from "../../../types/utils";

const WorkerPayloadSchema = z.object({
    url: z.string(),
    method: z.union([
        z.literal("get"),
        z.literal("post"),
        z.literal("put"),
        z.literal("patch"),
        z.literal("delete"),
    ]),
    body: z.record(z.string().or(z.number()), z.unknown()).optional(),
    headers: z.record(z.string(), z.string()).optional(),
    requestTimeoutSec: z.number().min(1).optional(),
});

export type WorkerPayload = z.infer<typeof WorkerPayloadSchema>;

export type WorkerResponse = MakeHttpJsonCallResponse;

export class ProcessHttpWorker extends ThreadWorker<WorkerPayload, Promise<WorkerResponse>> {
    constructor() {
        super(async (data) => await this.execute(data), {
            maxInactiveTime: 1000 * 60 * 2,
            killBehavior: "HARD",
        });
    }

    private async execute(data: WorkerPayload | undefined): Promise<WorkerResponse> {
        const valid = await WorkerPayloadSchema.safeParseAsync(data);

        if (!valid.success) {
            return {
                error: true,
                errors: {
                    message: valid.error.message,
                    cause: valid.error.cause,
                },
            };
        }

        const resp = await processTask(valid.data);
        if (resp.error) {
            return resp;
        }

        return {
            error: false,
            response: {
                body: resp.response.body,
                headers: resp.response.headers,
                statusCode: resp.response.statusCode,
                statusMessage: resp.response.statusMessage,
            },
        };
    }
}

export default new ProcessHttpWorker();
```

I have a scheduler([agenda](https://www.npmjs.com/package/agenda)) implemented to invoke this worker function, the concurrency for the job-processor / scheduler has similar limit i.e. MAX_POOL_SIZE = availableParallelism() > 1 ? availableParallelism() - 1 : 1

**Comment by jerome-benoit** [comment]
> Example Interface file -
> 
> ```ts
> import { DynamicThreadPool, availableParallelism } from "poolifier";
> const MAX_POOL_SIZE = availableParallelism() > 1 ? availableParallelism() - 1 : 1;

poolifier availableParallelism() always return a values higher or equal to 1. 

> 
> export const poolProcessHttp = new DynamicThreadPool<HttpWP, Promise<HttpWR>>(
>     0,

That's why the bug is happening. Until poolifier code is able to properly cope with no workers ready at tasks submission, you can set the min to 1 to avoid the issue. 

>     MAX_POOL_SIZE,
>     PROCESS_HTTP_WORKER_PATH,

**Comment by indrodev** [comment]
This throws error, can't set Dynamic Pool Min and Max value same, I had encountered this issue when I tried running on a 2 core / 2 thread CPU device. After that I set the min value to 0.
```typescript
import { DynamicThreadPool, availableParallelism } from "poolifier";
const MAX_POOL_SIZE = availableParallelism() > 1 ? availableParallelism() - 1 : 1;

export const poolProcessHttp = new DynamicThreadPool<HttpWP, Promise<HttpWR>>(
    1,
    1,
    PROCESS_HTTP_WORKER_PATH,
    {
        workerOptions: {
            name: "Http Worker",
        },
        errorHandler: (e: Error) => {
            logger.error("error in http worker %o", e);
            return e;
        },
        onlineHandler: () => {
            logger.info("HTTP Worker is online");
        },
    }
);
```

**Comment by jerome-benoit** [comment]
A dynamic pool with min = max is a fixed pool, hence the error. 
Why you do not set max to availableParallelism() (should be 2 and != from min)?

**Comment by indrodev** [comment]
Will replace max value to availableParallelism() - 1 -> availableParallelism(),  and min value to 1. Thanks for the guidance 😊

**Comment by jerome-benoit** [comment]
> Will replace max value to availableParallelism() - 1 -> availableParallelism(), and min value to 1. Thanks for the guidance 😊

It's a workaround, poolifier must handle properly min = 0.

**Comment by jerome-benoit** [comment]
I'm not totally convinced by the fix, so please reopen if it still occurs.

**Comment by indrodev** [comment]
Error: Worker node key chosen is null or undefined after 16 retries
    at X.executeStrategy (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:15851)
    at X.execute (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:15656)
    at exports.DynamicThreadPool.chooseWorkerNode (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:38730)
    at /usr/src/app/node_modules/poolifier/lib/index.cjs:1:35268
    at new Promise (<anonymous>)
    at exports.DynamicThreadPool.execute (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:34716)
    at HttpModeTask.process (/usr/src/app/dist/lib/Task/task.service.js:452:18)
    at HttpModeTask.execute (/usr/src/app/dist/lib/Task/task.service.js:266:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.processJob [as fn] (/usr/src/app/dist/utils/agenda/jobs/task.js:22:24) {
  [stack]: 'Error: Worker node key chosen is null or undefined after 16 retries\n' +
    '    at X.executeStrategy (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:15851)\n' +
    '    at X.execute (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:15656)\n' +
    '    at exports.DynamicThreadPool.chooseWorkerNode (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:38730)\n' +
    '    at /usr/src/app/node_modules/poolifier/lib/index.cjs:1:35268\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at exports.DynamicThreadPool.execute (/usr/src/app/node_modules/poolifier/lib/index.cjs:1:34716)\n' +
    '    at HttpModeTask.process (/usr/src/app/dist/lib/Task/task.service.js:452:18)\n' +
    '    at HttpModeTask.execute (/usr/src/app/dist/lib/Task/task.service.js:266:32)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.processJob [as fn] (/usr/src/app/dist/utils/agenda/jobs/task.js:22:24)',
  [message]: 'Worker node key chosen is null or undefined after 16 retries'
}

**Comment by jerome-benoit** [comment]
No worker has crashed before? And fail to restart?  
Because I do not see how it can happen with one minimum worker in the pool.

**Comment by indrodev** [comment]
Today I have made some modifications in the worker interface - 

```typescript
import { DynamicThreadPool, availableParallelism } from "poolifier";
const MAX_POOL_SIZE = availableParallelism();

export const poolProcessHttp = new DynamicThreadPool<HttpWP, Promise<HttpWR>>(
    1,
    MAX_POOL_SIZE,
    PROCESS_HTTP_WORKER_PATH,
    {
        // start
        enableTasksQueue: true,
        tasksQueueOptions: {
            concurrency: 8, // as per provided examples
        },
        // end ^ these task queue options 
        workerOptions: {
            name: "Http Worker",
        },
        errorHandler: (e: Error) => {
            logger.error("error in http worker %o", e);
            return e;
        },
        onlineHandler: () => {
            logger.info("HTTP Worker is online");
        },
    }
);
```

This error occurs when the workers are unable to perform a HTTP request (server down/unreachable). I have already handled HTTP request timeout + `maxInactiveTime: 1000 * 60 * 2` and `killBehavior: "HARD"` for worker options, so it should not block any workers.

**Comment by jerome-benoit** [comment]
Even if all workers are stuck in limbo, a worker shall be chosen unless they all crashed at the same time. Their queues will grow until an out of memory is triggered leading to a crash. But all of them crashing ... 

You should also ensure the HTTP client used is properly close in the killHandler on the worker side.

**Comment by indrodev** [comment]
I'm using `got` lib for making request

```typescript

export async function makeHttpJsonCall<
    RequestBody = Record<string | number, unknown> | undefined,
    ResponseBody = Record<string | number, unknown> | undefined,
>(payload: MakeHttpJsonCallPayload<RequestBody>): Promise<MakeHttpJsonCallResponse<ResponseBody>> {
    const options: OptionsOfJSONResponseBody = {
        method: payload.method,
        responseType: "json",
        timeout: {
            request:
                1000 *
                (typeof payload.requestTimeoutSec === "number" ? payload.requestTimeoutSec : 120), // 2 mins
        },
    };
    options.headers = { "trigger-from": "wms" };
    if ("headers" in payload) {
        options.headers = { ...options.headers, ...payload.headers };
    }

    if ("body" in payload && payload.body && typeof payload.body === "object") {
        options.json = payload.body;
    }
    // console.time("api time");
    try {
        const response = await got<ResponseBody>(new URL(payload.url), options);
        // console.timeEnd("api time");
        response?.destroy();
        return {
            error: false,
            response: {
                body: response.body,
                headers: response.headers,
                statusCode: response.statusCode,
                statusMessage: response.statusMessage,
            },
        };
    } catch (err) {
        const errorPayload: {
            message: string;
            statusCode?: number;
            body?: unknown;
            headers?: unknown;
            statusMessage?: string;
            cause: unknown;
        } = {
            message: "something went wrong",
            cause: {},
        };

        if (err instanceof HTTPError) {
            logger.warn("[Http Error] unable to make request -> %s", err.message);
            errorPayload.message = err.message;
            errorPayload.cause = err.cause;
            errorPayload.statusCode = err.response.statusCode;
            errorPayload.body = err.response.body;
            errorPayload.headers = err.response.headers;
            errorPayload.statusMessage = err.response.statusMessage;
            return { error: true, errors: errorPayload };
        }

        if (err instanceof RequestError) {
            logger.warn("[Request Error] unable to make request -> %s", err.message);
            errorPayload.message = err.message;
            errorPayload.cause = err.cause;
            errorPayload.statusCode = err.response?.statusCode;
            errorPayload.body = err.response?.body;
            return { error: true, errors: errorPayload };
        }
        // console.timeEnd("api time");
        const { message, stack, cause } = err as Error;
        logger.error("[Error] unable to make request -> %s", message);
        return {
            error: true,
            errors: {
                message,
                stack,
                cause,
            },
        };
    }
}

```

**Comment by jerome-benoit** [comment]
If `got` only require a `destroy()` call on the response to cleanup the resources used to perform a request, that should be fine. Otherwise you have a memory leak on the worker side.

**Comment by jerome-benoit** [comment]
I would also pre instantiate in a Map `got` instances with a size = concurrency. And reuse them to process requests to avoid the `got` instantiation overhead on the worker side. Unless `got` is already smart enough to cache instances at got invocation.

**Comment by indrodev** [comment]
This might be the issue -

By default, Got will retry on failure. To disable this option, set options.retry to 0.

**Comment by jerome-benoit** [comment]
Since it's not a poolifier bug, I reclose it. 

The discord is more appropriate for support request than GitHub issues.

**Comment by jerome-benoit** [comment]
Issue is not fixed. I now have a test to reproduce the issue.
