### ISSUE TITLE
[BUG] Could not find types (Common JS build using Typescript)

### ISSUE THREAD

**Issue by indrodev** [poolifier/poolifier#1821]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Typescript unable to find types when trying to build using `tsc`  TS -> JS [CommonJS]

### Expected behavior

no error

### Actual behavior

error TS7016: Could not find a declaration file for module 'poolifier'. '/.../node_modules/poolifier/lib/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/poolifier` if it exists or add a new declaration (.d.ts) file containing `declare module 'poolifier';`

7 import { DynamicThreadPool, availableParallelism } from "poolifier";
                                                          ~~~~~~~~~~~

### Steps to reproduce

TS Version - 5.3.3
tsconfig.json
```typescript
...
       "module": "CommonJS" /* Specify what module code is generated. */,
       "rootDir": "src" /* Specify the root folder within your source files. */,
       "moduleResolution": "Node10" /* Specify how TypeScript looks up a file from a given module specifier. */,
       "baseUrl": "." /* Specify the base directory to resolve non-relative module names. */,
...
```

### poolifier version

3.1.14

### Node.js version

v20.10.0

### System

  System:
    OS: Linux 5.15 Zorin OS 16.3
    CPU: (6) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 21.47 GB / 29.20 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh


### Attachments

_No response_

**Comment by jerome-benoit** [comment]
Hello, 

Could you please confirm that 3.1.15-0 pre-release works?

**Comment by indrodev** [comment]
yes, working no errors. Thanks

`Properly handle dynamic pool with zero minimum size.` will test it next

**Comment by jerome-benoit** [comment]
> yes, working no errors. Thanks

I will then do the 3.1.15 release with the fix.

**Comment by jerome-benoit** [comment]
Confirmed as fixed.
