### ISSUE TITLE
[FEATURE] Mapping operation API

### ISSUE THREAD

**Issue by tukkek** [poolifier/poolifier#2364]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

A common use for pools is to perform bulk parallel operations, wait for all of them to complete and then resume the program with all the results obtained. An example of this would be to perform slow, expensive parsing on a number of strings in parallel and then only proceed with the program once all of the items have been fully parsed. Pools are an ideal match for this type of use-case.

This is such a typical scenario for parallelization that many languages support it as a core feature. For example:
* Python: `multiprocessing.Pool().map(function,[data1,data2,data3])` https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.map
* Java: `List.of(data1,data2,data3).parallelStream().map(data->function(data)).toList()` https://javadoc.scijava.org/Java8/java/util/stream/Stream.html#map-java.util.function.Function-

I believe Poolifier would benefit from a `pool.map(datas,name,transfers)` method (similar to `pool.execute()`) that handles the creation and execution of bulk tasks to then return all results at once in an array so the program code can resume its work.

Without such a built-in method, Poolifier users will have to resort to creating the necessary boiler-plate code for every scenario that requires bulk fork-and-wait operations, possibly in multiple locations inside their program, making it time-consuming and error-prone. Other users may prefer to solve this by creating their own program-side implementation of `pool.map()`  - but then supporting it on the library itself would be a clear benefit rather than expecting them to write and test their own solution.

I appreciate your time and consideration in reviewing this feature request and big thanks to all involved with this project! It is, in my opinion, the best web-worker pool library available today.

**Comment by tukkek** [comment]
> * An API with a single helper `.map()`?

I'm not sure if you're making notes for posterity or asking me but if you are: the `map()` syntax is not only common to other major languages (and as such has been tried-and-tested by literally thousands of projects) - but is also native to JS's own `[].map()`.

It looks to me personally like the obvious choice, which is why I suggested it in the body and title of this issue.

> To allow to avoid to block the caller

In both of the use-cases I mentioned, the call is blocking. Python does have `multiprocessing.Pool().map_async()` but as the name shows, that is the secondary form of the function, not the main one.

As I had mentioned, the use-case for this function is "bulk fork-and-wait" operations. If you'd want to return a Promise instead, using `Promise.all()` is what I intend to do on my boiler-plate code, which I haven't got around to yet since writing this issue.

I apologize if I misunderstood your reply, I don't know anything about Deno, Bun or web-worker internals so I wouldn't be surprised if some of this stuff went above my head. Most of all, thank you very much for considering this feature! Cheers!

**Comment by jerome-benoit** [comment]
The comment was like a quick and dirty RFC for anyone interested ;)
It's intended to get the big picture, design and narrow down the API to the most common use cases before the implementation.

**Comment by tukkek** [comment]
I was working on a side-project during the weekend and took the time to write this issue rather than write my own `map()` program-side boiler-plate, so I ended up not quite getting to that. I don't know when I'll be able to resume work on that project again but if I get around to it before you do, I will share the code here - but I don't that'd be any time soon, unfortunately.

**Comment by jerome-benoit** [comment]
After more thoughts, the semantic of stream and iterable is orthogonal and can't be mixed in the same API. The same goes for blocking and non blocking. 

- Iterables: 
  - map()
  - mapAsync() ('Async' in the API namespace is misleading is node.js, its paradigm is async)

- Stream?

**Comment by tukkek** [comment]
Hello, I've seen `mapExecute()` made it to `poolifier-web-worker`! https://github.com/poolifier/poolifier-web-worker/blob/dba50c0825e339ca2d70968abf19bace9e957e46/src/pools/abstract-pool.ts#L1099

As such, I'll close this issue as solved.

If you'd like to re-open it for any house-keeping purposes, you are certainly able and welcome to do so!

Merci beaucoup Jérôme for your work and availability! I hope this new feature will be useful for your user-base as well! Have a great weekend!
