### ISSUE TITLE
[BUG] Cannot make to work websocket-server-pool/ws-cluster

### ISSUE THREAD

**Issue by st3ffgv4** [poolifier/poolifier#2368]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm just trying to run the  websocket-server-pool/ws-cluster example but it seems to not start the websocket server, the execute method seems to not run

### Expected behavior

Working example

### Actual behavior

Nothing happens

### Steps to reproduce

Just download the example, npm i, npm run build and then npm run start:esm

### poolifier version

4.0.14

### Node.js version

20.11.1

### System

 OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 17.68 GB / 31.77 GB

### Attachments

![image](https://github.com/poolifier/poolifier/assets/4953714/56fcfeca-35f6-44a8-8484-b3b0b33c620a)

**Comment by jerome-benoit** [comment]
Issue already reported: https://github.com/poolifier/poolifier/issues/782

**Comment by st3ffgv4** [comment]
@jerome-benoit so is it impossible to use this library in ESM mode?
