### ISSUE TITLE
Move poolifier repo to Poolifier organisation

### ISSUE THREAD

**Issue by jerome-benoit** [poolifier/poolifier#484]
Setup Poolifier https://github.com/poolifier org: 

- [x] Transfer existing repo under the org without complete recreation
- [x] Setup GH actions and npm delivery pipelines 

I can't do it on my own, especially the transfer. 

Next steps are: 

- [x] @pioardi: Add jerome-benoit@github user as an admin under sonacloud organisation for Poolifier;
- [x] Investigate why sonarcloud does not work anymore after the move. I need access to sonarcloud to investigate the issue: the scan now run in GH action but the report does not seem to be generated on PRs. Post create on sonarcloud fora: https://community.sonarsource.com/t/github-pr-sonarcloud-scan-status-wait-forever/48513
- [ ] Investigate if another admin can be added on npmjs as an admin for poolifier;
- [x] Is the documentation web pages domain transfered? Are they accessible?
- [x] Change URI in the code;
- [ ] @pioardi: npmjs and friends must now reference the new repo URI;

**Comment by Shinigami92** [comment]
Do you want to create a scoped org in npm?

But how should the packages be named? `@poolifier/core`?

**Comment by Shinigami92** [comment]
Also I'm not sure if I will directly jump into everything, but at least I already joined the newly created github org and mayb come around here and then, now and then

**Comment by pioardi** [comment]
I have joined the org, thanks @jerome-benoit  for creating it.
I will now transfer the repo, be ready !!! About npm for now I think we can keep it as it, the npm token secret should be transferred automatically to the new repo in the org.

**Comment by pioardi** [comment]
Doneeee

**Comment by jerome-benoit** [comment]
> Do you want to create a scoped org in npm?
> 
> But how should the packages be named? `@poolifier/core`?

What is gain? I'm not very familiar with npm setup.

**Comment by jerome-benoit** [comment]
Next steps are: 

+ Add Jérôme Benoit jerome-benoit@github as an admin under sonacloud org for Poolifier;
+ Is the documentation web pages domain transfered? Are they accessible?

**Comment by Shinigami92** [comment]
> > Do you want to create a scoped org in npm?
> > But how should the packages be named? `@poolifier/core`?
> 
> What is gain? I'm not very familiar with npm setup.

Nevermind, I didn't expect that pioardi respond and transfer the repo
So yeah, it's all good now and we can stay with the package name

**Comment by jerome-benoit** [comment]
@pioardi: sonarcloud does not work anymore after the move.

**Comment by jerome-benoit** [comment]
> Also I'm not sure if I will directly jump into everything, but at least I already joined the newly created github org and mayb come around here and then, now and then

If you're interested, I need help on CI, especially with dependabot and its secure integration.

**Comment by pioardi** [comment]
@jerome-benoit  I am unable to find your user on Sonar 
![image](https://user-images.githubusercontent.com/15161576/130411472-b6aecc91-01d6-4e21-858a-be0e740334aa.png)

I have added @Shinigami92  as owner of the org also
![image](https://user-images.githubusercontent.com/15161576/130411516-62d7a19c-247e-4ef0-ad94-e85a91a190d8.png)

**Comment by jerome-benoit** [comment]
> @jerome-benoit I am unable to find your user on Sonar
> ![image](https://user-images.githubusercontent.com/15161576/130411472-b6aecc91-01d6-4e21-858a-be0e740334aa.png)

I do not understand what is going on with my sonarcloud account, I assure you that I have one ;): 

https://sonarcloud.io/organizations/jerome-benoit/projects

**Comment by jerome-benoit** [comment]
@pioardi: You still do not see me on Sonar? even by just typing jerome?

**Comment by jerome-benoit** [comment]
@pioardi: I've fixed the sonarcloud reporting on PRs. Could you please move back all secrets at the repo level and remove the ones at the organisation level?
