### ISSUE TITLE
FEATURE_Add option for SHARE_ENV support to workers in worker-threads pool

### ISSUE THREAD

**Issue by jerome-benoit** [poolifier/poolifier#595]
See: https://nodejs.org/api/worker_threads.html#workershare_env

**Comment by pioardi** [comment]
Hi @jerome-benoit  I see that we already use the parent thread env variables https://github.com/poolifier/poolifier/blob/f821a8411ccb1217a6deb9d2e082eecc4ba6d9b4/src/pools/thread/fixed.ts#L75 

So is not clear to me what should we do here? Do we want to have an option to pass the SHARE_ENV or nor ? 

Alessandro

**Comment by jerome-benoit** [comment]
Yes, adding an option to enable or disable the env variables sharing can be useful.

**Comment by pioardi** [comment]
Thanks jerome
I will send a draft

**Comment by jerome-benoit** [comment]
Support for specific worker-threads options in thread pools includes it.
