### ISSUE TITLE
FEATURE_Move readme contents to wiki or site

### ISSUE THREAD

**Issue by rubiin** [poolifier/poolifier#608]
Currently on npm the package shows a size of `65 KB` and the readme alone sizes to `15 KB` . Thus making the readme minimum and moving the usage guidelines to wiki or website will help to size the whole library down by  around `20%`. 
Willing to help

**Comment by rubiin** [comment]
readme should be minimal like https://github.com/toonvanstrijp/nestjs-i18n

**Comment by rubiin** [comment]
Also this can be replaced with an enum  https://github.com/poolifier/poolifier/blob/898f36710ac4f137ffed7304fef7e4dc5c2621f0/src/worker/worker-options.ts#L4

**Comment by jerome-benoit** [comment]
> Also this can be replaced with an enum
> 
> https://github.com/poolifier/poolifier/blob/898f36710ac4f137ffed7304fef7e4dc5c2621f0/src/worker/worker-options.ts#L4

It's made that way on purpose: the transpiled code will always work for people using JS. @Shinigami92 has more explanations but I do not remember them from the top of head.

**Comment by namandeep-123** [comment]
Hey, Can you tell me more about it?

**Comment by jerome-benoit** [comment]
The wiki does not make really sense. Splitting some of the current README.md API content into the [typedoc](https://github.com/TypeStrong/typedoc) generated documentation in docs makes sense. I do not know if it's possible and how. 

I think the issue author means something like https://www.npmjs.com/package/ws with a ToC and links to other markdown files when a section content reach a certain level and should have a its own markdown file.

**Comment by rubiin** [comment]
@jerome-benoit something like this https://github.com/andywer/threads.js

**Comment by namandeep-123** [comment]
Okay. I got the idea; you can assign this task to me.

**Comment by namandeep-123** [comment]
@jerome-benoit How can I check for changes on my localhost?

**Comment by namandeep-123** [comment]
@jerome-benoit  I have created a file in Docs and shortened the readme.md file, please review it on my github sub-branch, and if there are any changes, tell me.

**Comment by rubiin** [comment]
create a pr

**Comment by namandeep-123** [comment]
Done
