### ISSUE TITLE
BUG_Typescript support not correct

### ISSUE THREAD

**Issue by ninimax** [poolifier/poolifier#632]
The Typescript example does not seem to be right. On one hand in WorkerPool it wants to import a '.js' file, on the other hand however the Worker itself is a .ts file.
It does not work to change in WorkerPool to find a file with .ts extension since the inner WorkerThread package would complain that .ts is not supported.

**Comment by jerome-benoit** [comment]
In that code: https://github.com/poolifier/poolifier/tree/master/examples/typescript, no '.js' files are imported and is tested to work. 
I doubt your TS setup is correct to properly transpile your .ts files before running them, no TS interpreter runtime hack like ts-node properly support worker-threads.

**Comment by jerome-benoit** [comment]
node.js runtime only interpret .js files. Each time you see TS code examples in projects, they are expected to be first transpiled by typescript before being interpreted by node.js. I think you can find TS initial setup to do TS code easily on Internet.

**Comment by ninimax** [comment]
OK, maybe we are talking about two different things. this is more what I meant https://github.com/TypeStrong/ts-node/issues/676#issuecomment-470898116. like, in a project, you can still have your worker as it is in Typescript... and I know how to setup TS ... :D

**Comment by jerome-benoit** [comment]
We do not support ugly hack to run TS code using worker-threads with ts-node. And do not plan to add such hack inside poolifier for obvious performance reason. But if the hack is only to mangle the worker file path and add an intermediate .js file, the class that encapsulate worker-threads worker in poolifier does not do any changes to the provided file path to init it. So the solution described in the issues should work with poolifier.
