### ISSUE TITLE
Strategies

### ISSUE THREAD

**Issue by ronag** [poolifier/poolifier#766]
I find the description of the different strategies a little unclear and would appreciate some clarifications.

> `WorkerChoiceStrategies.ROUND_ROBIN: Submit tasks to worker in a round robbin fashion`

This is clear.

> `WorkerChoiceStrategies.LEAST_USED: Submit tasks to the least used worker`

What does "`used`" mean? How is it measured?

> `WorkerChoiceStrategies.LEAST_BUSY: Submit tasks to the least busy worker`

What does "`busy`" mean? How is it measured?

> `WorkerChoiceStrategies.WEIGHTED_ROUND_ROBIN: Submit tasks to worker using a weighted round robin scheduling algorithm based on tasks execution time`

Unclear to me how this works...

> `WorkerChoiceStrategies.INTERLEAVED_WEIGHTED_ROUND_ROBIN: Submit tasks to worker using an interleaved weighted round robin scheduling algorithm based on tasks execution time (experimental)`

Unclear to me how this works...

> `WorkerChoiceStrategies.FAIR_SHARE: Submit tasks to worker using a fair share tasks scheduling algorithm based on tasks execution time`

Unclear to me how this works...

-------------------------------

On a different note. I would also like a scheduling algorithm where tasks are scheduled on the same thread/worker until event loop "lag" (configurable to e.g. 50ms) is detected at which point the next thread is spawned/used.

**Comment by jerome-benoit** [comment]
Regarding the documentation enhancement on strategies:
- some words short definition can be added or sentences can be rephrased.
- the most complex algorithm description is out of the scope of a README.md. Fair sharing on tasks execution time for example really summarizes the tasks scheduling behavior. I think the details must be added in a dedicated documentation. 

Regarding the new scheduling algorithm: could you please create a dedicated feature issue for it? 

Thanks.
