### ISSUE TITLE
FEATURE_Event Loop Utilization Strategy

### ISSUE THREAD

**Issue by ronag** [poolifier/poolifier#768]
Our use case for workers is to minimize latency (i.e. event loop lag) when running computationally heavy tasks. At the same time we want to minimize the number of threads.

I would like to propose a strategy that measures even loop lag of the works and schedules accordingly with a "max lag" option which will cause an additional worker to be spawned.

**Comment by jerome-benoit** [comment]
Since the worker choice is done at task submission, it's doable. 
Since I'm not familiar with the event loop statistics in node.js, do you know a way to compute the event  loop 'lag'?

**Comment by ronag** [comment]
See the examples section https://nodesource.com/blog/event-loop-utilization-nodejs/
